name: "Run rails server"
description: "Run rails server in the background for scans to access"
inputs:
  rails_env:
    description: RAILS_ENV to set. Defaults to ci
    required: false
    default: ci
  rails_master_key:
    description: decryption key for credentials file
    required: true
  database_url:
    description: DATABASE_URL to set
    required: true
runs:
  using: "composite"
  steps:
    - name: "Start server in background"
      shell: bash
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        DATABASE_URL: ${{ inputs.database_url }}
        RAILS_MASTER_KEY: ${{ inputs.rails_master_key }}
      run: bundle exec rails server &

    - name: "Wait for startup"
      shell: bash
      run: sleep 5

    - name: "Verify response working"
      shell: bash
      run: curl http://localhost:3000 -I
