name: Deploy Staging

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Deploy app
        uses: 18F/cg-deploy-action@main
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: tts-usps-test-at-home
          cf_space: sandbox
          push_arguments: >-
            --vars-file config/deployment/staging.yml
            --var rails_master_key=$RAILS_MASTER_KEY
